### ISSUE TITLE
rvcheck升级以后，不能安装yyplot了，'namespace:rvcheck'没有出口‘get_aes_var’这个对象（降级后解决）

### ISSUE THREAD

**Issue by swcyo** [GuangchuangYu/rvcheck#11]
最近重新安装yyplot
然而后面提示错误: 'namespace:rvcheck'没有出口‘get_aes_var’这个对象，是否是因为升级这个包了？？

>* installing *source* package ‘yyplot’ ...
>** using staged installation
>** R
>** byte-compile and prepare package for lazy loading
>错误: 'namespace:rvcheck'没有出口‘get_aes_var’这个对象
>停止执行
>ERROR: lazy loading failed for package ‘yyplot’
>* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/yyplot’
>Warning in install.packages :
>  installation of package ‘/Users/mac/Downloads/yyplot-master’ had non-zero exit status

**Comment by swcyo** [comment]
把**rvcheck**降级成0.1.8版以后，然后成功安装**yyplot**了，可能这是个BUG，希望解决

remotes::install_version("rvcheck",version = "0.1.8")

**Comment by GuangchuangYu** [comment]
fixed in `yyplot` v >= 0.0.9.

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/clusterProfiler/issues/374>.
