### ISSUE TITLE
"you need to upgrade your R first" when running rvcheck::update_all()

### ISSUE THREAD

**Issue by JackieMium** [GuangchuangYu/rvcheck#4]
I am using R on Linux and got `r-base-3.5.2.20190304-1` update few days ago. When I run `rvcheck::update_all()` just like I always do, it fails with an error message `Error in rvcheck::update_all() : you need to upgrade your R first...`.

![image](https://user-images.githubusercontent.com/12944832/53962998-58bfb700-4127-11e9-83a8-99ed5a8ca6ce.png)

Just to rule out internet problems, I've tried several times and none worked as expected.

I don't know why in the picture R says it's 3.5.3 but system package manager says it's 3.5.2:

```
➜  ~ dpkg -l |grep r-base
ii  r-base                                  3.5.2.20190304-1                all          GNU R statistical computation and graphics system
ii  r-base-core                             3.5.2.20190304-1                amd64        GNU R core of statistical computation and graphics system
ii  r-base-dev                              3.5.2.20190304-1                all          GNU R installation of auxiliary GNU R packages
ii  r-base-html                             3.5.2.20190304-1                all          GNU R html docs for statistical computing system functions
```

System: Debian sid amd64
R version: r-base-3.5.2.20190304-1

**Comment by GuangchuangYu** [comment]
pls use `rvcheck::update_all(check_R = FALSE)`.
