### ISSUE TITLE
check_github got '400 Bad Request'

### ISSUE THREAD

**Issue by tarouikemen** [GuangchuangYu/rvcheck#8]
When I tried to check version of dplyr package by check_github() on R 4.0.2 and rvcheck 0.1.8, getting error with message below.

_cannot open URL 'https://raw.githubusercontent.com/dplyr/master/DESCRIPTION': HTTP status was '400 Bad Request'_

Other functions such as check_cran or check_r works fine. Is there any solution ?

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/89391315-9cfb2080-d73a-11ea-8b83-306811dda640.png)
